# .github/workflows/run-tests.yml
name: Scheduled Test Run

on:
  schedule:
    - cron: '50 10 * * *'  # every day at 9am UTC
  workflow_dispatch:      # optional: lets you trigger manually via UI

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout suite
        uses: actions/checkout@v3

      - name: Set up Java (example)
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run Tests
        run: mvn test  # replace with your actual test command

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports
